name: "InterfaceKit CI"

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  iOS:
    name: Test iOS
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer
    strategy:
      matrix:
        destination: ["OS=14.4,name=iPhone 12 Pro"] #, "OS=12.4,name=iPhone XS", "OS=11.4,name=iPhone X", "OS=10.3.1,name=iPhone SE"]
    steps:
      - uses: actions/checkout@master
      - name: Install Firewalk
        run: brew install InterfaceKit/InterfaceKit/firewalk && firewalk &
      - name: iOS - ${{ matrix.destination }}
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "InterfaceKit.xcodeproj" -scheme "InterfaceKit" -destination "${{ matrix.destination }}" clean test | xcpretty
  watchOS:
    name: Build watchOS
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer
    strategy:
      matrix:
        destination: ["OS=7.2,name=Apple Watch Series 6 - 44mm"] #, "OS=4.2,name=Apple Watch Series 3 - 42mm", "OS=3.2,name=Apple Watch Series 2 - 42mm"]
    steps:
      - uses: actions/checkout@master
      - name: watchOS - ${{ matrix.destination }}
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "InterfaceKit.xcodeproj" -scheme "InterfaceKit" -destination "${{ matrix.destination }}" clean build | xcpretty
  spm:
    name: Test with SPM
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer
    steps:
      - uses: actions/checkout@master
      - name: Install Firewalk
        run: brew install InterfaceKit/InterfaceKit/firewalk && firewalk &
      - name: SPM Test
        run: swift test -c debug
